### ISSUE TITLE
make help message more comprehensive

### ISSUE THREAD

**Issue by FerallOut** [core-unit-bioinformatics/cubi-tools#50] opened 2024-04-04 13:57 UTC
When creating a new git repo using 'auto_git.py', I think it would be helpful to rephrase certain explanations. For example:

- it would be helpful to add to the "--norm NORM, -n NORM Normalize git remotes." the fact that it only applies to already existent repositories.

- when documenting the use of identity files ("--git-identities IDENTITIES, -g IDENTITIES"), it would be helpful to know what they should look like. To create a repo only for the HHU gitlab, the file should be called "githhu.id" and have just 2 lines: name (used for push to target) and your email address (in this case, your HHU address).

- it might help to have an example after the options are discussed, similar to:
`./auto_git.py -i ~/path_to_dir/repo_name_that_conforms_to_CUBI_rules -ip githhu -d`

- also add that in order to push, you would need the '-u' option
`git push -u`

**Comment by ptrebert** [comment] 2024-04-15 06:54
re 1) fixed in 2bc4d1b
re 2) duplicate of #28, already addressed via readme update in 51a70f045831a0dcb3f3730a83305197fdf90a1b and cli help update in 8098c3fd73830118d3930eb2e8589d7fb9e7e9be
re 3) fixed in 86e2f93
re 4) added usage hints in 7041507, can be omitted with new cli option `--quiet`; in version 0.2

**Closed by ptrebert** 2024-04-15 06:54 UTC
